Resources:
  webserverSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: webserver SG
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

  webserver:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []

          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

    Properties:
      ImageId: ami-7c87d913
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref webserverSG
      UserData:
        Fn::Base64:
          !Sub  |
          #!/bin/bash -eux
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -r webserver -s ${AWS::StackId} --region ${AWS::Region} -v
Outputs:
  webserverPublicIPAddress:
    Value: !Sub ${webserver.PublicIp}
